#Write a program to input eight numbers from the user and display all the unique
# numbers (once).
n1 = set()
s1 = int(input("Enter the number 1 : "))
n1.add(int(s1))
s2 = int(input("Enter the number 2 : "))
n1.add(int(s2))
s3 = int(input("Enter the number 3 : "))
n1.add(int(s3))
s4 = int(input("Enter the number 4 : "))
n1.add(int(s4))
s5 = int(input("Enter the number 5 : "))
n1.add(int(s5))
s6 = int(input("Enter the number 6 : "))
n1.add(int(s6))
s7 = int(input("Enter the number 7 : "))
n1.add(int(s7))
s8 = int(input("Enter the number 8 : "))
n1.add(int(s8))
print(n1)