# If languages of two friends are same; what will happen to the program in problem
# 6?


dic = {}

name = input("Enter the name  : ")
lan =  input("Enter the  laguage:")
dic.update({name:lan})

name = input("Enter the name  : ")
lan =  input("Enter the  laguage:")
dic.update({name:lan})

name = input("Enter the name  : ")
lan =  input("Enter the  laguage:")
dic.update({name:lan})

name = input("Enter the name  : ")
lan =  input("Enter the  laguage:")
dic.update({name:lan})

print(dic)

# IF THE LANGUAGE OF 2 FRIENDS ARE SAME SO THAT WILL NOT MAKE ANY DIFFERENCE BECUASE ONLY THE VALUE IS SAME BUT THE KEY IS DIFFERENT WHICH IS THE PARENT ELEMENT 
